{% set name = "rastervision-aws-batch" %}
{% set version = "0.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rastervision_aws_batch-{{ version }}.tar.gz
  sha256: 8568f3f97b1400fe966e88c9a1a8aaeeb836cffeadab376ae427a116f027bce6
  patches:
    - 0001-fix-imports.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rastervision=rastervision.aws_batch.aws_batch_runner:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - awscli
    - boto3
    - python >=3.6
    - rastervision-pipeline ==0.13.1

test:
  imports:
    - rastervision.aws_batch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/azavea/raster-vision
  summary: A rastervision plugin that adds an AWS Batch pipeline runner
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - psortos
